#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
HTML_DIR="$ROOT_DIR/public/stitch/html"
SCREENSHOT_DIR="$ROOT_DIR/public/stitch/screenshots"
DOCS_DIR="$ROOT_DIR/docs/stitch"

mkdir -p "$HTML_DIR" "$SCREENSHOT_DIR" "$DOCS_DIR"

download() {
  local url="$1"
  local output="$2"
  curl -L "$url" -o "$output"
}

# Landing Page
download "https://lh3.googleusercontent.com/aida/ADBb0ug0Fm_tKtBsL3iOcZ8dWA1IOBMAfZ66Z8qFnuuIo4MUVHO_zgfFvA93WRgixotc8BSd6zLEW2qLoWnxoBXy50GdyyBfSArvgLM_c75_YX6sHw4gkQDzJygZZzE0w-ascuranh_Jv4MikhsPfuQJX3hnd0KOHrVdN0XmYK9-A6oIbfzxASwqNfzuJmazIsNZLAiME39efjl-LVxZH2SCOo9jSGkrPpREbQYJ9OGZEKkFzOW-F2qMoX09FtKx" "$SCREENSHOT_DIR/landing-page.png"
download "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzM0MDMxYTJlNDVkNzQ4MzBiOTVhNDUzMWYzODUzYWYxEgsSBxDZ8bXw6w4YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzQwNzgzMzYyODQwODYwODMwOA&filename=&opi=89354086" "$HTML_DIR/landing-page.html"

# Evaluation Dashboard
download "https://lh3.googleusercontent.com/aida/ADBb0ugwYXG3PHKBlI4zXzQ0GIlFZaKgxCWzU8A0afzvDjKQ8KJolsHAVzbcAFbAuAG_1RpQJmyed9P0I-gdFOqiCirQUC438foQfQnI3y3RLxKiy5pXMQy5KAeHA0OKXpJSJO6Cg4PhrWPWUkJp7c21qZGzolngAO4p0MnqFLff8coHJYlGpkz4yxzcAJyuG9afKI6qTK8xu0YLwIyD7EDRpn_50Ahp0p0oqm7FZBn48P1LcIgNANTEj5ttu5g" "$SCREENSHOT_DIR/evaluation-dashboard.png"
download "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzAwMDY0ZDY5MjhiM2M2YzcwMzM4NTIxNjUyMmY1YjQ4EgsSBxDZ8bXw6w4YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzQwNzgzMzYyODQwODYwODMwOA&filename=&opi=89354086" "$HTML_DIR/evaluation-dashboard.html"

# Evaluation History
download "https://lh3.googleusercontent.com/aida/ADBb0ugV8hOH5q20wMm_R89WqM6mKcmAu-v9-ez9FynoUeh3SkAlU0ce-WIFuMPI6g3WrhqK-2nfPt5uSK1L_Kx3ONqlnp4BlKcrqIcbJ4bCoLy7ivfVYZ2mcVSwMoeTNc6dmzJDftwQdp8leMYi6kkkJPmJKyFtXstKQh4Adk2pnH8r8S0hVd0KUvFLlFN_T1sjMK53OkrYbEnk5FS_vYEjp5kdqI-f47sV2tjyyliizgeGpEx4mAV3UjovWx3T" "$SCREENSHOT_DIR/evaluation-history.png"
download "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2Y2NGI4MTc4OGU1NzQyMmM5ZTg4ZGIwNGU1NjM1YzQzEgsSBxDZ8bXw6w4YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzQwNzgzMzYyODQwODYwODMwOA&filename=&opi=89354086" "$HTML_DIR/evaluation-history.html"

# Settings
download "https://lh3.googleusercontent.com/aida/ADBb0ui0dqYNAA6Rso8kJXcCuXzwaUEgMJT0O56fPdTAe-69nq3C6-D5eZFkRDI67ijJiGyIehH-B7z8U1EGnW0ej33Wl2-DCgtx84blm6mqZR-5xrqS4vrlwLFjSb4sGkEEUB-HmPMKs4IwjmGG3yI_w7hu50TL6NG21wOXJ3pv9c6sRNQmLiMaNVPS7Dnrf-9ZTeFv8W0XX5v2ws5jMsJutgQzbsjJ8ERwUpMGmfLAptDf1M8-sLUD-tcS_H2a" "$SCREENSHOT_DIR/settings.png"
download "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzM2ODBhODlhMjhlMzQyODY5NDJiNDAyNDQyNGRkM2Y3EgsSBxDZ8bXw6w4YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzQwNzgzMzYyODQwODYwODMwOA&filename=&opi=89354086" "$HTML_DIR/settings.html"

# Policy Management
download "https://lh3.googleusercontent.com/aida/ADBb0uiJr692r3e57_MQb5T8uEJinagbvgmD94DEkSXCO5NiHPi-QsGfQeOH0QYuh9L9EzFcLBXfWf00Lr09OPgNUmppUpzWjA0MnpipJVGB1N_gv60vVXbop1qTFul4r0tCevpyWLvD9x1ivq6EJFmptWmp-UlUa1N4XhjtHrbuY-_ddGG0mISHkymcVQ9EzytuT_MH2b2lCk9q7SXjIiHyVdLa4HiaknC5y1XGZzJvbUAz5mNPXHsrtEXXPsIf" "$SCREENSHOT_DIR/policy-management.png"
download "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2YyOTIwMWYwY2Y3YzQzYzE4ZDIwN2MxM2I2OWViYzEyEgsSBxDZ8bXw6w4YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzQwNzgzMzYyODQwODYwODMwOA&filename=&opi=89354086" "$HTML_DIR/policy-management.html"

# Help Center
download "https://lh3.googleusercontent.com/aida/ADBb0uiu59rN398dUFWNAg0s31WGk1tKuNIpEX6M0fuM4CzyeRvGkH7Nki_p9-rjYOIimtXlbBUgbY02iArPznLRbOZ8X2ab2WYO4ZrpudOeDdmTmTjk-BxmOHXbW_a6GWyP2yIlpmZNwoV8BlQXEfEJFPiN8cOoir8NFEiDSxEPgrwlXdxPhgJwT3jyVavXZYGu_I6yw66O_nEhpGWUq-dj4zizx01wzYrSPYvGAyKGoG7nYoRlZhUbYwi5Sh8" "$SCREENSHOT_DIR/help-center.png"
download "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzgxMjFiMGY0MGY0YTQ2N2Q4ZjE5YjZjMTE3MDdmN2U3EgsSBxDZ8bXw6w4YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzQwNzgzMzYyODQwODYwODMwOA&filename=&opi=89354086" "$HTML_DIR/help-center.html"

# Support Access
download "https://lh3.googleusercontent.com/aida/ADBb0uj4oZn3YJtkLtClqKQRdyqTtAWoEwMoCoQjBygUcgq7wBlykAJ4Bo0L7-_mj2MD13KD3CK74p3OXz73Lt64eMhHTnPoKsO9jrnZ8ovO1KaOCGCGK3rB-zvkbz2L4gnFx-YFGBSEnIwIF3QUhIPvDsDwaEAS8NSD2fAxVMgo3gMP4TdbF5Wk2lngBnW4hY7euPGQEMRuK_5hhslDEUa-eSqQjJfvHcy5XDNhn8rlf-NSGy2r528bJRXeiXGk" "$SCREENSHOT_DIR/support-access.png"
download "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzJlZmQ5YTY4NzIyMTRiNjk4YjJkNWNiNGFmYjgzYzRmEgsSBxDZ8bXw6w4YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzQwNzgzMzYyODQwODYwODMwOA&filename=&opi=89354086" "$HTML_DIR/support-access.html"

# Request Service
download "https://lh3.googleusercontent.com/aida/ADBb0ujqkF3vLqduH0l7BrvONY4Qxa3LQrU-k2Xu_seQUmjFij36u0u7_5FtqieGh2ZQcEZiAyNP--mqsBCdHoyth0YexGT_66Dmgdg2MjzZ6gjkBS-pwdxeIqnvs4ruZzb7T9q-WYLTh8qz__l9fcVXTKjW8-SDPw4yQT9xstGgYJY-MVpWEf8RPycmKlChQW3bdDimCYiRkR_vdscIr5YwyT5MsJ1wdPEGXSKD2OmWPykIp4hCxnJs1KScLMvg" "$SCREENSHOT_DIR/request-service.png"
download "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzU2NmFjYWNlYWE4MDQyMzRiZjVmMDM0Mjc4M2YyMDA3EgsSBxDZ8bXw6w4YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzQwNzgzMzYyODQwODYwODMwOA&filename=&opi=89354086" "$HTML_DIR/request-service.html"

# Add Security Policy Modal
download "https://lh3.googleusercontent.com/aida/ADBb0uhj8VNmfrkPGqw3Bb1USH86edN_BaJCHR4GMnBDbGORY65BE2aeKanNQD5v8y7KnojU0yF4X5MwiIp_6tpP7OO3a2ygHUaxA0ga02KJxG9E_G5bSr6UqG8L6e9UJgCNW7wpOaHaeE6jmGKP-kbKwm6rtj8ZtuPPez_gHpmsZILfKvKaGLq7zSGnOa6Hb2nlrLXrcb0Z65YJnczhnrDohFncAcS861xVFFlOSvseT9KsoG32hVGVojzD_ILy" "$SCREENSHOT_DIR/add-security-policy-modal.png"
download "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzVlZTUxNzE1NWVhNzRmMzNhZDk1MDZmOTkzNTA0MGYxEgsSBxDZ8bXw6w4YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzQwNzgzMzYyODQwODYwODMwOA&filename=&opi=89354086" "$HTML_DIR/add-security-policy-modal.html"

# Decision Result
download "https://lh3.googleusercontent.com/aida/ADBb0uj_lIBY0EQAflcycF87_sCObJG9ZMdmWTLmf0eh02jCVuW7H8yKtohhJR53MdAIV2ivRXhMzIvSZYjgSp6ubP9p2YV_QQ9vi309fnRABoDX4szRzi3PqmeP95eaa30-bWTzCYb-tkU4gxtIgtf--76R-FfpvKjxFSih7OZ2xED3JLLE8pp2FkifufPYnq4jh_LOhLI8mHeuiKtvJ0OsgXqoH5Z7JYt4Ib0IsEQkLtQdaFjskpgN3xPm-LRl" "$SCREENSHOT_DIR/decision-result.png"
download "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzE1ZTc4MmQ2MzQ3OTQ1YWQ5N2Q0ZjJkYTY5MTU2YjQ1EgsSBxDZ8bXw6w4YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzQwNzgzMzYyODQwODYwODMwOA&filename=&opi=89354086" "$HTML_DIR/decision-result.html"

echo "Downloaded Stitch exports into $HTML_DIR and $SCREENSHOT_DIR"
