/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportAccessRouteImport } from './routes/support-access'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as RequestServiceRouteImport } from './routes/request-service'
import { Route as PolicyManagementRouteImport } from './routes/policy-management'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as EvaluationHistoryRouteImport } from './routes/evaluation-history'
import { Route as EvaluationDashboardRouteImport } from './routes/evaluation-dashboard'
import { Route as DecisionResultRouteImport } from './routes/decision-result'
import { Route as AddSecurityPolicyModalRouteImport } from './routes/add-security-policy-modal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPoliciesRouteImport } from './routes/api/policies'
import { Route as ApiEvaluationsRouteImport } from './routes/api/evaluations'
import { Route as ApiX402DiscoveryRouteImport } from './routes/api/x402/discovery'
import { Route as ApiReceiptsReceiptIdRouteImport } from './routes/api/receipts/$receiptId'
import { Route as ApiPoliciesPolicyIdRouteImport } from './routes/api/policies.$policyId'
import { Route as ApiEvaluationsIdRouteImport } from './routes/api/evaluations/$id'
import { Route as ApiEvaluateServiceRouteImport } from './routes/api/evaluate/service'
import { Route as ApiEvaluateDemoRouteImport } from './routes/api/evaluate/demo'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthChallengeRouteImport } from './routes/api/auth/challenge'
import { Route as ApiAgentLogsReceiptIdRouteImport } from './routes/api/agent-logs/$receiptId'
import { Route as ApiPoliciesPolicyIdArchiveRouteImport } from './routes/api/policies.$policyId.archive'
import { Route as ApiPoliciesPolicyIdActivateRouteImport } from './routes/api/policies.$policyId.activate'
import { Route as ApiEvaluationsIdPrivateRouteImport } from './routes/api/evaluations/$id.private'

const SupportAccessRoute = SupportAccessRouteImport.update({
  id: '/support-access',
  path: '/support-access',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestServiceRoute = RequestServiceRouteImport.update({
  id: '/request-service',
  path: '/request-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyManagementRoute = PolicyManagementRouteImport.update({
  id: '/policy-management',
  path: '/policy-management',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationHistoryRoute = EvaluationHistoryRouteImport.update({
  id: '/evaluation-history',
  path: '/evaluation-history',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationDashboardRoute = EvaluationDashboardRouteImport.update({
  id: '/evaluation-dashboard',
  path: '/evaluation-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionResultRoute = DecisionResultRouteImport.update({
  id: '/decision-result',
  path: '/decision-result',
  getParentRoute: () => rootRouteImport,
} as any)
const AddSecurityPolicyModalRoute = AddSecurityPolicyModalRouteImport.update({
  id: '/add-security-policy-modal',
  path: '/add-security-policy-modal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoliciesRoute = ApiPoliciesRouteImport.update({
  id: '/api/policies',
  path: '/api/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluationsRoute = ApiEvaluationsRouteImport.update({
  id: '/api/evaluations',
  path: '/api/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiX402DiscoveryRoute = ApiX402DiscoveryRouteImport.update({
  id: '/api/x402/discovery',
  path: '/api/x402/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptsReceiptIdRoute = ApiReceiptsReceiptIdRouteImport.update({
  id: '/api/receipts/$receiptId',
  path: '/api/receipts/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoliciesPolicyIdRoute = ApiPoliciesPolicyIdRouteImport.update({
  id: '/$policyId',
  path: '/$policyId',
  getParentRoute: () => ApiPoliciesRoute,
} as any)
const ApiEvaluationsIdRoute = ApiEvaluationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEvaluationsRoute,
} as any)
const ApiEvaluateServiceRoute = ApiEvaluateServiceRouteImport.update({
  id: '/api/evaluate/service',
  path: '/api/evaluate/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluateDemoRoute = ApiEvaluateDemoRouteImport.update({
  id: '/api/evaluate/demo',
  path: '/api/evaluate/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChallengeRoute = ApiAuthChallengeRouteImport.update({
  id: '/api/auth/challenge',
  path: '/api/auth/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentLogsReceiptIdRoute = ApiAgentLogsReceiptIdRouteImport.update({
  id: '/api/agent-logs/$receiptId',
  path: '/api/agent-logs/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoliciesPolicyIdArchiveRoute =
  ApiPoliciesPolicyIdArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => ApiPoliciesPolicyIdRoute,
  } as any)
const ApiPoliciesPolicyIdActivateRoute =
  ApiPoliciesPolicyIdActivateRouteImport.update({
    id: '/activate',
    path: '/activate',
    getParentRoute: () => ApiPoliciesPolicyIdRoute,
  } as any)
const ApiEvaluationsIdPrivateRoute = ApiEvaluationsIdPrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => ApiEvaluationsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-security-policy-modal': typeof AddSecurityPolicyModalRoute
  '/decision-result': typeof DecisionResultRoute
  '/evaluation-dashboard': typeof EvaluationDashboardRoute
  '/evaluation-history': typeof EvaluationHistoryRoute
  '/help-center': typeof HelpCenterRoute
  '/policy-management': typeof PolicyManagementRoute
  '/request-service': typeof RequestServiceRoute
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/support-access': typeof SupportAccessRoute
  '/api/evaluations': typeof ApiEvaluationsRouteWithChildren
  '/api/policies': typeof ApiPoliciesRouteWithChildren
  '/api/agent-logs/$receiptId': typeof ApiAgentLogsReceiptIdRoute
  '/api/auth/challenge': typeof ApiAuthChallengeRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/evaluate/demo': typeof ApiEvaluateDemoRoute
  '/api/evaluate/service': typeof ApiEvaluateServiceRoute
  '/api/evaluations/$id': typeof ApiEvaluationsIdRouteWithChildren
  '/api/policies/$policyId': typeof ApiPoliciesPolicyIdRouteWithChildren
  '/api/receipts/$receiptId': typeof ApiReceiptsReceiptIdRoute
  '/api/x402/discovery': typeof ApiX402DiscoveryRoute
  '/api/evaluations/$id/private': typeof ApiEvaluationsIdPrivateRoute
  '/api/policies/$policyId/activate': typeof ApiPoliciesPolicyIdActivateRoute
  '/api/policies/$policyId/archive': typeof ApiPoliciesPolicyIdArchiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-security-policy-modal': typeof AddSecurityPolicyModalRoute
  '/decision-result': typeof DecisionResultRoute
  '/evaluation-dashboard': typeof EvaluationDashboardRoute
  '/evaluation-history': typeof EvaluationHistoryRoute
  '/help-center': typeof HelpCenterRoute
  '/policy-management': typeof PolicyManagementRoute
  '/request-service': typeof RequestServiceRoute
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/support-access': typeof SupportAccessRoute
  '/api/evaluations': typeof ApiEvaluationsRouteWithChildren
  '/api/policies': typeof ApiPoliciesRouteWithChildren
  '/api/agent-logs/$receiptId': typeof ApiAgentLogsReceiptIdRoute
  '/api/auth/challenge': typeof ApiAuthChallengeRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/evaluate/demo': typeof ApiEvaluateDemoRoute
  '/api/evaluate/service': typeof ApiEvaluateServiceRoute
  '/api/evaluations/$id': typeof ApiEvaluationsIdRouteWithChildren
  '/api/policies/$policyId': typeof ApiPoliciesPolicyIdRouteWithChildren
  '/api/receipts/$receiptId': typeof ApiReceiptsReceiptIdRoute
  '/api/x402/discovery': typeof ApiX402DiscoveryRoute
  '/api/evaluations/$id/private': typeof ApiEvaluationsIdPrivateRoute
  '/api/policies/$policyId/activate': typeof ApiPoliciesPolicyIdActivateRoute
  '/api/policies/$policyId/archive': typeof ApiPoliciesPolicyIdArchiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-security-policy-modal': typeof AddSecurityPolicyModalRoute
  '/decision-result': typeof DecisionResultRoute
  '/evaluation-dashboard': typeof EvaluationDashboardRoute
  '/evaluation-history': typeof EvaluationHistoryRoute
  '/help-center': typeof HelpCenterRoute
  '/policy-management': typeof PolicyManagementRoute
  '/request-service': typeof RequestServiceRoute
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/support-access': typeof SupportAccessRoute
  '/api/evaluations': typeof ApiEvaluationsRouteWithChildren
  '/api/policies': typeof ApiPoliciesRouteWithChildren
  '/api/agent-logs/$receiptId': typeof ApiAgentLogsReceiptIdRoute
  '/api/auth/challenge': typeof ApiAuthChallengeRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/evaluate/demo': typeof ApiEvaluateDemoRoute
  '/api/evaluate/service': typeof ApiEvaluateServiceRoute
  '/api/evaluations/$id': typeof ApiEvaluationsIdRouteWithChildren
  '/api/policies/$policyId': typeof ApiPoliciesPolicyIdRouteWithChildren
  '/api/receipts/$receiptId': typeof ApiReceiptsReceiptIdRoute
  '/api/x402/discovery': typeof ApiX402DiscoveryRoute
  '/api/evaluations/$id/private': typeof ApiEvaluationsIdPrivateRoute
  '/api/policies/$policyId/activate': typeof ApiPoliciesPolicyIdActivateRoute
  '/api/policies/$policyId/archive': typeof ApiPoliciesPolicyIdArchiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-security-policy-modal'
    | '/decision-result'
    | '/evaluation-dashboard'
    | '/evaluation-history'
    | '/help-center'
    | '/policy-management'
    | '/request-service'
    | '/screens'
    | '/settings'
    | '/support-access'
    | '/api/evaluations'
    | '/api/policies'
    | '/api/agent-logs/$receiptId'
    | '/api/auth/challenge'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/verify'
    | '/api/evaluate/demo'
    | '/api/evaluate/service'
    | '/api/evaluations/$id'
    | '/api/policies/$policyId'
    | '/api/receipts/$receiptId'
    | '/api/x402/discovery'
    | '/api/evaluations/$id/private'
    | '/api/policies/$policyId/activate'
    | '/api/policies/$policyId/archive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-security-policy-modal'
    | '/decision-result'
    | '/evaluation-dashboard'
    | '/evaluation-history'
    | '/help-center'
    | '/policy-management'
    | '/request-service'
    | '/screens'
    | '/settings'
    | '/support-access'
    | '/api/evaluations'
    | '/api/policies'
    | '/api/agent-logs/$receiptId'
    | '/api/auth/challenge'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/verify'
    | '/api/evaluate/demo'
    | '/api/evaluate/service'
    | '/api/evaluations/$id'
    | '/api/policies/$policyId'
    | '/api/receipts/$receiptId'
    | '/api/x402/discovery'
    | '/api/evaluations/$id/private'
    | '/api/policies/$policyId/activate'
    | '/api/policies/$policyId/archive'
  id:
    | '__root__'
    | '/'
    | '/add-security-policy-modal'
    | '/decision-result'
    | '/evaluation-dashboard'
    | '/evaluation-history'
    | '/help-center'
    | '/policy-management'
    | '/request-service'
    | '/screens'
    | '/settings'
    | '/support-access'
    | '/api/evaluations'
    | '/api/policies'
    | '/api/agent-logs/$receiptId'
    | '/api/auth/challenge'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/verify'
    | '/api/evaluate/demo'
    | '/api/evaluate/service'
    | '/api/evaluations/$id'
    | '/api/policies/$policyId'
    | '/api/receipts/$receiptId'
    | '/api/x402/discovery'
    | '/api/evaluations/$id/private'
    | '/api/policies/$policyId/activate'
    | '/api/policies/$policyId/archive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddSecurityPolicyModalRoute: typeof AddSecurityPolicyModalRoute
  DecisionResultRoute: typeof DecisionResultRoute
  EvaluationDashboardRoute: typeof EvaluationDashboardRoute
  EvaluationHistoryRoute: typeof EvaluationHistoryRoute
  HelpCenterRoute: typeof HelpCenterRoute
  PolicyManagementRoute: typeof PolicyManagementRoute
  RequestServiceRoute: typeof RequestServiceRoute
  ScreensRoute: typeof ScreensRoute
  SettingsRoute: typeof SettingsRoute
  SupportAccessRoute: typeof SupportAccessRoute
  ApiEvaluationsRoute: typeof ApiEvaluationsRouteWithChildren
  ApiPoliciesRoute: typeof ApiPoliciesRouteWithChildren
  ApiAgentLogsReceiptIdRoute: typeof ApiAgentLogsReceiptIdRoute
  ApiAuthChallengeRoute: typeof ApiAuthChallengeRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiEvaluateDemoRoute: typeof ApiEvaluateDemoRoute
  ApiEvaluateServiceRoute: typeof ApiEvaluateServiceRoute
  ApiReceiptsReceiptIdRoute: typeof ApiReceiptsReceiptIdRoute
  ApiX402DiscoveryRoute: typeof ApiX402DiscoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support-access': {
      id: '/support-access'
      path: '/support-access'
      fullPath: '/support-access'
      preLoaderRoute: typeof SupportAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-service': {
      id: '/request-service'
      path: '/request-service'
      fullPath: '/request-service'
      preLoaderRoute: typeof RequestServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-management': {
      id: '/policy-management'
      path: '/policy-management'
      fullPath: '/policy-management'
      preLoaderRoute: typeof PolicyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation-history': {
      id: '/evaluation-history'
      path: '/evaluation-history'
      fullPath: '/evaluation-history'
      preLoaderRoute: typeof EvaluationHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation-dashboard': {
      id: '/evaluation-dashboard'
      path: '/evaluation-dashboard'
      fullPath: '/evaluation-dashboard'
      preLoaderRoute: typeof EvaluationDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-result': {
      id: '/decision-result'
      path: '/decision-result'
      fullPath: '/decision-result'
      preLoaderRoute: typeof DecisionResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-security-policy-modal': {
      id: '/add-security-policy-modal'
      path: '/add-security-policy-modal'
      fullPath: '/add-security-policy-modal'
      preLoaderRoute: typeof AddSecurityPolicyModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policies': {
      id: '/api/policies'
      path: '/api/policies'
      fullPath: '/api/policies'
      preLoaderRoute: typeof ApiPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluations': {
      id: '/api/evaluations'
      path: '/api/evaluations'
      fullPath: '/api/evaluations'
      preLoaderRoute: typeof ApiEvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/discovery': {
      id: '/api/x402/discovery'
      path: '/api/x402/discovery'
      fullPath: '/api/x402/discovery'
      preLoaderRoute: typeof ApiX402DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipts/$receiptId': {
      id: '/api/receipts/$receiptId'
      path: '/api/receipts/$receiptId'
      fullPath: '/api/receipts/$receiptId'
      preLoaderRoute: typeof ApiReceiptsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policies/$policyId': {
      id: '/api/policies/$policyId'
      path: '/$policyId'
      fullPath: '/api/policies/$policyId'
      preLoaderRoute: typeof ApiPoliciesPolicyIdRouteImport
      parentRoute: typeof ApiPoliciesRoute
    }
    '/api/evaluations/$id': {
      id: '/api/evaluations/$id'
      path: '/$id'
      fullPath: '/api/evaluations/$id'
      preLoaderRoute: typeof ApiEvaluationsIdRouteImport
      parentRoute: typeof ApiEvaluationsRoute
    }
    '/api/evaluate/service': {
      id: '/api/evaluate/service'
      path: '/api/evaluate/service'
      fullPath: '/api/evaluate/service'
      preLoaderRoute: typeof ApiEvaluateServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluate/demo': {
      id: '/api/evaluate/demo'
      path: '/api/evaluate/demo'
      fullPath: '/api/evaluate/demo'
      preLoaderRoute: typeof ApiEvaluateDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/challenge': {
      id: '/api/auth/challenge'
      path: '/api/auth/challenge'
      fullPath: '/api/auth/challenge'
      preLoaderRoute: typeof ApiAuthChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-logs/$receiptId': {
      id: '/api/agent-logs/$receiptId'
      path: '/api/agent-logs/$receiptId'
      fullPath: '/api/agent-logs/$receiptId'
      preLoaderRoute: typeof ApiAgentLogsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policies/$policyId/archive': {
      id: '/api/policies/$policyId/archive'
      path: '/archive'
      fullPath: '/api/policies/$policyId/archive'
      preLoaderRoute: typeof ApiPoliciesPolicyIdArchiveRouteImport
      parentRoute: typeof ApiPoliciesPolicyIdRoute
    }
    '/api/policies/$policyId/activate': {
      id: '/api/policies/$policyId/activate'
      path: '/activate'
      fullPath: '/api/policies/$policyId/activate'
      preLoaderRoute: typeof ApiPoliciesPolicyIdActivateRouteImport
      parentRoute: typeof ApiPoliciesPolicyIdRoute
    }
    '/api/evaluations/$id/private': {
      id: '/api/evaluations/$id/private'
      path: '/private'
      fullPath: '/api/evaluations/$id/private'
      preLoaderRoute: typeof ApiEvaluationsIdPrivateRouteImport
      parentRoute: typeof ApiEvaluationsIdRoute
    }
  }
}

interface ApiEvaluationsIdRouteChildren {
  ApiEvaluationsIdPrivateRoute: typeof ApiEvaluationsIdPrivateRoute
}

const ApiEvaluationsIdRouteChildren: ApiEvaluationsIdRouteChildren = {
  ApiEvaluationsIdPrivateRoute: ApiEvaluationsIdPrivateRoute,
}

const ApiEvaluationsIdRouteWithChildren =
  ApiEvaluationsIdRoute._addFileChildren(ApiEvaluationsIdRouteChildren)

interface ApiEvaluationsRouteChildren {
  ApiEvaluationsIdRoute: typeof ApiEvaluationsIdRouteWithChildren
}

const ApiEvaluationsRouteChildren: ApiEvaluationsRouteChildren = {
  ApiEvaluationsIdRoute: ApiEvaluationsIdRouteWithChildren,
}

const ApiEvaluationsRouteWithChildren = ApiEvaluationsRoute._addFileChildren(
  ApiEvaluationsRouteChildren,
)

interface ApiPoliciesPolicyIdRouteChildren {
  ApiPoliciesPolicyIdActivateRoute: typeof ApiPoliciesPolicyIdActivateRoute
  ApiPoliciesPolicyIdArchiveRoute: typeof ApiPoliciesPolicyIdArchiveRoute
}

const ApiPoliciesPolicyIdRouteChildren: ApiPoliciesPolicyIdRouteChildren = {
  ApiPoliciesPolicyIdActivateRoute: ApiPoliciesPolicyIdActivateRoute,
  ApiPoliciesPolicyIdArchiveRoute: ApiPoliciesPolicyIdArchiveRoute,
}

const ApiPoliciesPolicyIdRouteWithChildren =
  ApiPoliciesPolicyIdRoute._addFileChildren(ApiPoliciesPolicyIdRouteChildren)

interface ApiPoliciesRouteChildren {
  ApiPoliciesPolicyIdRoute: typeof ApiPoliciesPolicyIdRouteWithChildren
}

const ApiPoliciesRouteChildren: ApiPoliciesRouteChildren = {
  ApiPoliciesPolicyIdRoute: ApiPoliciesPolicyIdRouteWithChildren,
}

const ApiPoliciesRouteWithChildren = ApiPoliciesRoute._addFileChildren(
  ApiPoliciesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddSecurityPolicyModalRoute: AddSecurityPolicyModalRoute,
  DecisionResultRoute: DecisionResultRoute,
  EvaluationDashboardRoute: EvaluationDashboardRoute,
  EvaluationHistoryRoute: EvaluationHistoryRoute,
  HelpCenterRoute: HelpCenterRoute,
  PolicyManagementRoute: PolicyManagementRoute,
  RequestServiceRoute: RequestServiceRoute,
  ScreensRoute: ScreensRoute,
  SettingsRoute: SettingsRoute,
  SupportAccessRoute: SupportAccessRoute,
  ApiEvaluationsRoute: ApiEvaluationsRouteWithChildren,
  ApiPoliciesRoute: ApiPoliciesRouteWithChildren,
  ApiAgentLogsReceiptIdRoute: ApiAgentLogsReceiptIdRoute,
  ApiAuthChallengeRoute: ApiAuthChallengeRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiEvaluateDemoRoute: ApiEvaluateDemoRoute,
  ApiEvaluateServiceRoute: ApiEvaluateServiceRoute,
  ApiReceiptsReceiptIdRoute: ApiReceiptsReceiptIdRoute,
  ApiX402DiscoveryRoute: ApiX402DiscoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
