/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportAccessRouteImport } from './routes/support-access'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as RequestServiceRouteImport } from './routes/request-service'
import { Route as PolicyManagementRouteImport } from './routes/policy-management'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as EvaluationHistoryRouteImport } from './routes/evaluation-history'
import { Route as EvaluationDashboardRouteImport } from './routes/evaluation-dashboard'
import { Route as DecisionResultRouteImport } from './routes/decision-result'
import { Route as AddSecurityPolicyModalRouteImport } from './routes/add-security-policy-modal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiX402DiscoveryRouteImport } from './routes/api/x402/discovery'
import { Route as ApiReceiptsReceiptIdRouteImport } from './routes/api/receipts/$receiptId'
import { Route as ApiEvaluateServiceRouteImport } from './routes/api/evaluate/service'
import { Route as ApiEvaluateDemoRouteImport } from './routes/api/evaluate/demo'
import { Route as ApiAgentLogsReceiptIdRouteImport } from './routes/api/agent-logs/$receiptId'

const SupportAccessRoute = SupportAccessRouteImport.update({
  id: '/support-access',
  path: '/support-access',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestServiceRoute = RequestServiceRouteImport.update({
  id: '/request-service',
  path: '/request-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyManagementRoute = PolicyManagementRouteImport.update({
  id: '/policy-management',
  path: '/policy-management',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationHistoryRoute = EvaluationHistoryRouteImport.update({
  id: '/evaluation-history',
  path: '/evaluation-history',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationDashboardRoute = EvaluationDashboardRouteImport.update({
  id: '/evaluation-dashboard',
  path: '/evaluation-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionResultRoute = DecisionResultRouteImport.update({
  id: '/decision-result',
  path: '/decision-result',
  getParentRoute: () => rootRouteImport,
} as any)
const AddSecurityPolicyModalRoute = AddSecurityPolicyModalRouteImport.update({
  id: '/add-security-policy-modal',
  path: '/add-security-policy-modal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiX402DiscoveryRoute = ApiX402DiscoveryRouteImport.update({
  id: '/api/x402/discovery',
  path: '/api/x402/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptsReceiptIdRoute = ApiReceiptsReceiptIdRouteImport.update({
  id: '/api/receipts/$receiptId',
  path: '/api/receipts/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluateServiceRoute = ApiEvaluateServiceRouteImport.update({
  id: '/api/evaluate/service',
  path: '/api/evaluate/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluateDemoRoute = ApiEvaluateDemoRouteImport.update({
  id: '/api/evaluate/demo',
  path: '/api/evaluate/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentLogsReceiptIdRoute = ApiAgentLogsReceiptIdRouteImport.update({
  id: '/api/agent-logs/$receiptId',
  path: '/api/agent-logs/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-security-policy-modal': typeof AddSecurityPolicyModalRoute
  '/decision-result': typeof DecisionResultRoute
  '/evaluation-dashboard': typeof EvaluationDashboardRoute
  '/evaluation-history': typeof EvaluationHistoryRoute
  '/help-center': typeof HelpCenterRoute
  '/policy-management': typeof PolicyManagementRoute
  '/request-service': typeof RequestServiceRoute
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/support-access': typeof SupportAccessRoute
  '/api/agent-logs/$receiptId': typeof ApiAgentLogsReceiptIdRoute
  '/api/evaluate/demo': typeof ApiEvaluateDemoRoute
  '/api/evaluate/service': typeof ApiEvaluateServiceRoute
  '/api/receipts/$receiptId': typeof ApiReceiptsReceiptIdRoute
  '/api/x402/discovery': typeof ApiX402DiscoveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-security-policy-modal': typeof AddSecurityPolicyModalRoute
  '/decision-result': typeof DecisionResultRoute
  '/evaluation-dashboard': typeof EvaluationDashboardRoute
  '/evaluation-history': typeof EvaluationHistoryRoute
  '/help-center': typeof HelpCenterRoute
  '/policy-management': typeof PolicyManagementRoute
  '/request-service': typeof RequestServiceRoute
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/support-access': typeof SupportAccessRoute
  '/api/agent-logs/$receiptId': typeof ApiAgentLogsReceiptIdRoute
  '/api/evaluate/demo': typeof ApiEvaluateDemoRoute
  '/api/evaluate/service': typeof ApiEvaluateServiceRoute
  '/api/receipts/$receiptId': typeof ApiReceiptsReceiptIdRoute
  '/api/x402/discovery': typeof ApiX402DiscoveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-security-policy-modal': typeof AddSecurityPolicyModalRoute
  '/decision-result': typeof DecisionResultRoute
  '/evaluation-dashboard': typeof EvaluationDashboardRoute
  '/evaluation-history': typeof EvaluationHistoryRoute
  '/help-center': typeof HelpCenterRoute
  '/policy-management': typeof PolicyManagementRoute
  '/request-service': typeof RequestServiceRoute
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/support-access': typeof SupportAccessRoute
  '/api/agent-logs/$receiptId': typeof ApiAgentLogsReceiptIdRoute
  '/api/evaluate/demo': typeof ApiEvaluateDemoRoute
  '/api/evaluate/service': typeof ApiEvaluateServiceRoute
  '/api/receipts/$receiptId': typeof ApiReceiptsReceiptIdRoute
  '/api/x402/discovery': typeof ApiX402DiscoveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-security-policy-modal'
    | '/decision-result'
    | '/evaluation-dashboard'
    | '/evaluation-history'
    | '/help-center'
    | '/policy-management'
    | '/request-service'
    | '/screens'
    | '/settings'
    | '/support-access'
    | '/api/agent-logs/$receiptId'
    | '/api/evaluate/demo'
    | '/api/evaluate/service'
    | '/api/receipts/$receiptId'
    | '/api/x402/discovery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-security-policy-modal'
    | '/decision-result'
    | '/evaluation-dashboard'
    | '/evaluation-history'
    | '/help-center'
    | '/policy-management'
    | '/request-service'
    | '/screens'
    | '/settings'
    | '/support-access'
    | '/api/agent-logs/$receiptId'
    | '/api/evaluate/demo'
    | '/api/evaluate/service'
    | '/api/receipts/$receiptId'
    | '/api/x402/discovery'
  id:
    | '__root__'
    | '/'
    | '/add-security-policy-modal'
    | '/decision-result'
    | '/evaluation-dashboard'
    | '/evaluation-history'
    | '/help-center'
    | '/policy-management'
    | '/request-service'
    | '/screens'
    | '/settings'
    | '/support-access'
    | '/api/agent-logs/$receiptId'
    | '/api/evaluate/demo'
    | '/api/evaluate/service'
    | '/api/receipts/$receiptId'
    | '/api/x402/discovery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddSecurityPolicyModalRoute: typeof AddSecurityPolicyModalRoute
  DecisionResultRoute: typeof DecisionResultRoute
  EvaluationDashboardRoute: typeof EvaluationDashboardRoute
  EvaluationHistoryRoute: typeof EvaluationHistoryRoute
  HelpCenterRoute: typeof HelpCenterRoute
  PolicyManagementRoute: typeof PolicyManagementRoute
  RequestServiceRoute: typeof RequestServiceRoute
  ScreensRoute: typeof ScreensRoute
  SettingsRoute: typeof SettingsRoute
  SupportAccessRoute: typeof SupportAccessRoute
  ApiAgentLogsReceiptIdRoute: typeof ApiAgentLogsReceiptIdRoute
  ApiEvaluateDemoRoute: typeof ApiEvaluateDemoRoute
  ApiEvaluateServiceRoute: typeof ApiEvaluateServiceRoute
  ApiReceiptsReceiptIdRoute: typeof ApiReceiptsReceiptIdRoute
  ApiX402DiscoveryRoute: typeof ApiX402DiscoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support-access': {
      id: '/support-access'
      path: '/support-access'
      fullPath: '/support-access'
      preLoaderRoute: typeof SupportAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-service': {
      id: '/request-service'
      path: '/request-service'
      fullPath: '/request-service'
      preLoaderRoute: typeof RequestServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-management': {
      id: '/policy-management'
      path: '/policy-management'
      fullPath: '/policy-management'
      preLoaderRoute: typeof PolicyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation-history': {
      id: '/evaluation-history'
      path: '/evaluation-history'
      fullPath: '/evaluation-history'
      preLoaderRoute: typeof EvaluationHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation-dashboard': {
      id: '/evaluation-dashboard'
      path: '/evaluation-dashboard'
      fullPath: '/evaluation-dashboard'
      preLoaderRoute: typeof EvaluationDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-result': {
      id: '/decision-result'
      path: '/decision-result'
      fullPath: '/decision-result'
      preLoaderRoute: typeof DecisionResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-security-policy-modal': {
      id: '/add-security-policy-modal'
      path: '/add-security-policy-modal'
      fullPath: '/add-security-policy-modal'
      preLoaderRoute: typeof AddSecurityPolicyModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/discovery': {
      id: '/api/x402/discovery'
      path: '/api/x402/discovery'
      fullPath: '/api/x402/discovery'
      preLoaderRoute: typeof ApiX402DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipts/$receiptId': {
      id: '/api/receipts/$receiptId'
      path: '/api/receipts/$receiptId'
      fullPath: '/api/receipts/$receiptId'
      preLoaderRoute: typeof ApiReceiptsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluate/service': {
      id: '/api/evaluate/service'
      path: '/api/evaluate/service'
      fullPath: '/api/evaluate/service'
      preLoaderRoute: typeof ApiEvaluateServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluate/demo': {
      id: '/api/evaluate/demo'
      path: '/api/evaluate/demo'
      fullPath: '/api/evaluate/demo'
      preLoaderRoute: typeof ApiEvaluateDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-logs/$receiptId': {
      id: '/api/agent-logs/$receiptId'
      path: '/api/agent-logs/$receiptId'
      fullPath: '/api/agent-logs/$receiptId'
      preLoaderRoute: typeof ApiAgentLogsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddSecurityPolicyModalRoute: AddSecurityPolicyModalRoute,
  DecisionResultRoute: DecisionResultRoute,
  EvaluationDashboardRoute: EvaluationDashboardRoute,
  EvaluationHistoryRoute: EvaluationHistoryRoute,
  HelpCenterRoute: HelpCenterRoute,
  PolicyManagementRoute: PolicyManagementRoute,
  RequestServiceRoute: RequestServiceRoute,
  ScreensRoute: ScreensRoute,
  SettingsRoute: SettingsRoute,
  SupportAccessRoute: SupportAccessRoute,
  ApiAgentLogsReceiptIdRoute: ApiAgentLogsReceiptIdRoute,
  ApiEvaluateDemoRoute: ApiEvaluateDemoRoute,
  ApiEvaluateServiceRoute: ApiEvaluateServiceRoute,
  ApiReceiptsReceiptIdRoute: ApiReceiptsReceiptIdRoute,
  ApiX402DiscoveryRoute: ApiX402DiscoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
